webdev/tarefas/urls.py
from webdev.tarefas import views
from django.urls import path

app_name='tarefas'

urlpatterns=[
    path('', views.home, name='home'),
    path('<int:tarefa_id>', views.detalhe, name='detalhe'),  #<int:tarefa_id>aqui mostra que tarefa_id é um numero inteiro, parece que esta guardando a tarefa do view detalhe
    path('apagar/<int:tarefa_id>', views.apagar, name='apagar'), #aqui esta apagando
]
#aqui são os caminhos dentro do aplicativo tarefas, que estão detalhados em views

webdev/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from webdev.tarefas import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home),
    path('tarefas/', include('webdev.tarefas.urls')),
]

webdev/tarefas/models.py
from django.db import models

# Create your models here.
class Tarefa(models.Model):
    nome = models.CharField(max_length=128)
    feita = models.BooleanField(default=False)

webdev/tarefas/forms.py
from webdev.tarefas.models import Tarefa
from django.forms import ModelForm
#acho que toda vez que utilizamos form (formulario) temos fazer esse modulo forms
class TarefaNovaForm(ModelForm): #com esse formulario nos vamos validar os dados e salvar no banco de dados
    class Meta:
        model = Tarefa           #importamos o model Tarefa
        fields = ['nome']        #esse formulario ele atribui o nome

class TarefaForm(ModelForm):     # esse formularo ira lidar com todos campos das tarefas, diferente do outro formulario acima
    class Meta:
        model = Tarefa
        fields = ['nome', 'feita']   # além do nome, aqui no caso para indicar se a tarefa foi feita ou não

webdev/tarefas/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect

from webdev.tarefas.forms import TarefaNovaForm, TarefaForm
from django.urls import reverse

from webdev.tarefas.models import Tarefa


def home(request):
    if request.method == 'POST':                                         # esse metodo ele publica, manda msg
        form = TarefaNovaForm(request.POST)                              #estamos acessando os dados de "TarefaNovaForm" atraves do request.POST e passando isso para a variavel form
        if form.is_valid():                                              #se formulario é valido, salva o formulario dentro do nosso banco de dados
            form.save()
            return HttpResponseRedirect(reverse('tarefas:home'))        #retornar http redirect reverter em tarefas:home
        else:                                                           #outra
            tarefas_pendentes = Tarefa.objects.filter(feita=False).all()   #acessando no banco de dados as tarefas não feitas e passando para variavel "tarefas_pendentes"
            tarefas_feitas = Tarefa.objects.filter(feita=True).all()       #acessando no banco de dados as tarefas feitas e passando para minha variavel "tarefas_feitas"
            return render(request, 'tarefas/home.html',       #aqui estamos reenderizando a informação para o template tarefas/home.html
                          {'form': form, 'tarefas_pendentes': tarefas_pendentes, 'tarefas_feitas': tarefas_feitas, },
                          status=400)                                     #aqui estamos ligando nossas variaveis com as do html, esse status 400 é código de erro caso o usuario tente salvar a tarefa com o campo em branco, ai ira aparecer uma msg de erro abaixo do campo. O form : form que passamos no contexto acima e não passamos no contexto abaixo, também é referente a msg de erro que, ele auxilia para mostrar a msg de erro {{ form.nome.errors }}
    tarefas_pendentes = Tarefa.objects.filter(feita=False).all()          #acessando no banco de dados as tarefas não feitas e passando para variavel "tarefas_pendentes"
    tarefas_feitas = Tarefa.objects.filter(feita=True).all()              #acessando no banco de dados as tarefas feitas e passando para variavel "tarefas_feitas"
    return render(request, 'tarefas/home.html',
                  {'tarefas_pendentes': tarefas_pendentes, 'tarefas_feitas': tarefas_feitas, })


# Create your views here.

def detalhe(request, tarefa_id):                   #acho que eles colocaram tarefa_id como parametro na função pois, essa função e a de baixo recebem as tarefas, agora a função def home apenas cria a tarefa.
    if request.method == 'POST':                     #metodo pubiclar
        tarefa = Tarefa.objects.get(id=tarefa_id)   # variavel tarefa, buscando no banco de dados os id da tarefa que vamos editar
        form = TarefaForm(request.POST, instance=tarefa)  #variavel form, estamos passando o dicionario post com todos os dados "request.POST". E também vamos passar a instancia que vamos editar no caso tarefa
        if form.is_valid():                            # formulario é valido , salva o formulario
            form.save()
    return HttpResponseRedirect(reverse('tarefas:home'))     #e redireciona para "tarefa:home" que é o nome da app + def home de veiw


def apagar(request, tarefa_id):
    if request.method == 'POST':                      #metodo pubiclar
        Tarefa.objects.filter(id=tarefa_id).delete()  # aqui esta deletando o id da tarefa, que automaticamente deleta a tarefa
    return HttpResponseRedirect(reverse('tarefas:home'))   #depois redireciona para tarefa:home

webdev/tarefas/templates/tarefas/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">  <!--configuração de css-->
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2"> <!--aqui estamos alinhando o texto-->
            <h1 class="mt-5">Lista de Tarefas</h1>   <!--aqui estamos dando uma margem para o topo da pagina, e colocando titulo em h1 titulo do campo-->

            <form action="{% url 'tarefas:home' %}" method="post">  <!--estou utilizando o metodo post para envio de dados, que estamos enviando para "tarefa:home"-->
                {% csrf_token %}

                <div class="input-group mb-3">
                    <input type="text" class="form-control" placeholder="Descreva sua tarefa"
                           aria-label="Descreva sua tarefa" aria-describedby="button-addon2" name="nome">  <!--esse name="nome" é o nome da minha propriedade, e é por esse parametro que vamos obter os dados do formulario-->

                    <button type="submit" class="btn btn-primary" type="button" id="button-addon2">Salvar</button>  <!--botão salvar-->

                </div>
                <small class="form-text text-muted">{{ form.nome.errors }}</small>    <!--essa é msg de erro que aperece embaixo do formulario salvar, se por acaso tentar salvar o formulario em branco-->
            </form>                                                     <!--fechando o form aqui-->
            <h2 class="mt-5">Tarefas Pendentes</h2>   <!--titulo do campo-->

            {% for tarefa in tarefas_pendentes %}   <!--aqui esta separando as tarefas recebidas de tarefas home, por unidades-->
            <form action="{% url 'tarefas:detalhe' tarefa_id=tarefa.id %}" method="post">      <!--abrindo o form, 'tarefas:detalhe' o endereço da url. tarefa_id=tarefa.id passando o id , esse tarefa.id é justamente o tarefa do for acima -->
                {% csrf_token %}

                <div class="input-group mb-3">
                    <input type="text" class="form-control" placeholder="Descreva sua tarefa" required="required"
                           aria-label="Descreva sua tarefa" name="nome" value="{{ tarefa.nome }}">  <!--esse value="{{ tarefa.nome }} é para o nome da tarefa ficar visivel dentro do formulario Tarefa Pendente, assim que o usuario salvar no campo Lista de Tarefa"-->
                    <input type="hidden" value="checked" name="feita">  <!--esse feita é o nome da proriedade no modelo (acho que quer dizer nome da tag input). Esse "value="checked"" é um checked box, aqueles campos de marcação com v-->

                    <div class="input-group-append">
                        <button type="submit" class="btn btn-success">Marcar como feita</button> <!--botão de marcar como feita-->
                    </div>
                </div>

            </form>                                       <!--fechando o form-->

            {% endfor %}

            <h2 class="mt-5">Tarefas ja Concluidas</h2>  <!--titulo do campo-->

            {% for tarefa in tarefas_feitas %} <!--separando as tarefas recebidas de Tarefas Pendentes, por unidade-->
            <div class="row">
                <div class="col-2">
                    <form action="{% url 'tarefas:apagar' tarefa_id=tarefa.id %}" method="post"> <!--ação de apagar as tarefas, abrindo o form-->
                        {% csrf_token %}

                        <div class="input-group mb-3">

                            <div class="input-group-append">
                                <button type="submit" class="btn btn-danger">Apagar</button> <!--botão apagar-->
                            </div>
                        </div>

                    </form><!--fechando o form-->
                </div>
                <div class="col-10">
                    <form action="{% url 'tarefas:detalhe' tarefa_id=tarefa.id %}" method="post">  <!--devolvendo para tarefa:detalhe as tarefas marcadas como pendentes. Abrindo o form-->
                        {% csrf_token %}

                        <div class="input-group mb-3">
                            <input type="text" class="form-control" placeholder="Descreva sua tarefa"
                                   required="required"
                                   aria-label="Descreva sua tarefa" name="nome" value="{{ tarefa.nome }}"> <!--esse value="{{ tarefa.nome }} é para o nome da tarefa ficar visivel dentro do formulario Tarefa concluidas, assim que o usuario salvar no campo tarefa pendente"-->


                            <div class="input-group-append">
                                <button type="submit" class="btn btn-warning">Marcar como Pendente</button> <!--botão de retornar a tarefa para a tarefa pendente-->
                            </div>
                        </div>

                    </form> <!--fechando o form-->
                </div>


            </div>


            {% endfor %}
        </div>


    </div>


</div>

</body>
</html>